import {
  SUPABASE_URL,
  SUPABASE_API_KEY,
  GOOGLE_MAPS_API_KEY,
  WEB_CLIENT_ID,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  FACEBOOK_APP_ID,
  ANDROID_CLIENT_ID_2,
  ANDROID_CLIENT_ID_3,
  ANDROID_CLIENT_ID_4,
} from "@env";

export default {
  SUPABASE_API_KEY,
  SUPABASE_URL,
  GOOGLE_MAPS_API_KEY,
  WEB_CLIENT_ID,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  FACEBOOK_APP_ID,
  ANDROID_CLIENT_ID_2,
  ANDROID_CLIENT_ID_3,
  ANDROID_CLIENT_ID_4,
};
