import {
  SUPABASE_URL,
  SUPABASE_API_KEY,
  GOOGLE_MAPS_API_KEY,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  FACEBOOK_APP_ID,
} from "@env";

export default {
  SUPABASE_API_KEY,
  SUPABASE_URL,
  GOOGLE_MAPS_API_KEY,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  FACEBOOK_APP_ID,
};
